[package]
name = "dna-assets"
version = "0.1.0"
authors = ["BlockX Labs <info0@blockxlabs.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sr-primitives = { git = "https://github.com/blockxlabs/substrate", default-features = false }
srml-support = { git = "https://github.com/blockxlabs/substrate", default-features = false, package="frame-support" }
system = { package = "frame-system", git = "https://github.com/blockxlabs/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/blockxlabs/substrate", default-features = false }

[dev-dependencies]
substrate-primitives = { git = "https://github.com/blockxlabs/substrate" }
runtime-io = { package = "sr-io", git = "https://github.com/blockxlabs/substrate" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sr-primitives/std",
	"srml-support/std",
	"system/std",
	"rstd/std",
	"substrate-primitives/std",
]