[package]
name = "dna"
version = "0.1.0"
authors = ["BlockX Labs info@blockxlabs.com"]
build = "node/cli/build.rs"
edition = "2018"

[[bin]]
name = "dna"
path = "node/cli/bin/main.rs"

[dependencies]
error-chain = "0.12"
dna-cli = { path = "node/cli", package = "dna-cli" }
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }

[build-dependencies]
vergen = "3.0.4"
structopt = "0.3.3"
build-script-utils = { package = "substrate-build-script-utils", git = "https://github.com/blockxlabs/substrate.git" }


[workspace]
members = [
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/rpc-client",
	"node/rpc",
	"node/runtime",
	"node/testing",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
