[dependencies]
error-chain = '0.12'
exit-future = '0.1'
futures = '0.1'
hex-literal = '0.1'
log = '0.4'
parity-codec = '3.2'
parking_lot = '0.7.1'
tokio = '0.1'
trie-root = '0.12.0'
serde_json = '1.0.0'


[dependencies.basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-basic-authorship'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-inherents'

[dependencies.network]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-network'

[dependencies.dna-runtime]
path = 'runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'

[dependencies.sr-io]
git = 'https://github.com/paritytech/substrate.git'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate.git'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate.git'

[dependencies.substrate-executor]
git = 'https://github.com/paritytech/substrate.git'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate.git'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-transaction-pool'

[dependencies.substrate-telemetry]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-telemetry'

[[bin]]
name = 'dna'
path = 'src/main.rs'

[build-dependencies]
vergen = '3'

[profile.dev]
panic = 'unwind'  
incremental = true

[profile.release]
panic = 'unwind'
incremental = false

[profile.test]
debug = 2
panic = 'unwind'
incremental = true

[profile.bench]
panic = 'unwind'
incremental = false


[package]
authors = ['Parity Technologies <admin@parity.io>']
build = 'build.rs'
edition = '2018'
name = 'dna'
version = '1.0.0'
