[workspace]
members = [
	"node/cli",
	"node/executor",
	"node/primitives",
	"node/rpc-client",
	"node/rpc",
	"node/runtime",
	"node/testing",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
