[package]
name = "dna-staking"
version = "0.0.1"
edition = "2018"

[dependencies]
sp-staking = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
staking = { package = "pallet-staking", git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
primitives = { package = "sp-core", git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }
sp-keyring = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev", optional = true }
sp-std = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
sp-phragmen = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
sp-io ={ git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
sp-runtime = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
frame-support = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
frame-system = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
pallet-session = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
pallet-authorship = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }

[dev-dependencies]
sp-core = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
pallet-balances = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
pallet-timestamp = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
pallet-staking-reward-curve = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }
substrate-test-utils = { git = "https://github.com/blockxlabs/substrate", default-features = false, branch = "blockx-dev" }

[features]
migrate = []
default = ["std"]
std = [
	"serde",
	"sp-keyring",
	"codec/std",
	"sp-std/std",
	"sp-phragmen/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
]